server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  application:
    name: resource-server

  sleuth:
    # 采样率的概率，100%采样
    sampler:
      probability: 1.0
      # 每秒采样数字最高为1000
      rate: 1000